PROJECT: x_pcie
working_path: "syn_results"
module: x_pcie
verilog_file_list: "C:/lscc/diamond/3.12/cae_library/synthesis/verilog/ecp5um.v"
verilog_file_list: "C:/lscc/diamond/3.12/cae_library/synthesis/verilog/pmi_def.v"
verilog_file_list: "../x_pcie_core_bb.v"
verilog_file_list: "../x_pcie.v"
verilog_file_list: "../pcie_eval/models/ecp5um/x_pcie_pcs_softlogic.v"
verilog_file_list: "../pcie_eval/models/ecp5um/x_pcie_pcs.v"
verilog_file_list: "../pcie_eval/models/ecp5um/x_pcie_sync1s.v"
verilog_file_list: "../pcie_eval/models/ecp5um/x_pcie_ctc.v"
verilog_file_list: "../pcie_eval/models/ecp5um/x_pcie_pipe.v"
verilog_file_list: "../pcie_eval/models/ecp5um/x_pcie_phy.v"
resource_sharing: false
write_verilog: true
write_vhdl: false
suffix_name: edi
output_file_name: x_pcie
write_prf: false
vlog_std_v2001: true
disable_io_insertion: true
force_gsr: false
speed_grade: 8
frequency: 125.000
fanout_limit: 100
retiming: false
pipe: false
fixgatedclocks: 0
fixgeneratedclocks: 0
