//Verilog instantiation template

pcie_x1_e5 _inst (.x_pcie_bus_num(), .x_pcie_cmd_reg_out(), .x_pcie_dev_cntl_out(), 
           .x_pcie_dev_num(), .x_pcie_func_num(), .x_pcie_lnk_cntl_out(), 
           .x_pcie_mm_enable(), .x_pcie_msi(), .x_pcie_npd_num_vc0(), 
           .x_pcie_pd_num_vc0(), .x_pcie_phy_ltssm_state(), .x_pcie_pm_power_state(), 
           .x_pcie_rx_bar_hit(), .x_pcie_rx_data_vc0(), .x_pcie_rx_lbk_data(), 
           .x_pcie_rx_lbk_kcntl(), .x_pcie_rxdp_dllp_val(), .x_pcie_rxdp_pmd_type(), 
           .x_pcie_rxdp_vsd_data(), .x_pcie_sci_addr(), .x_pcie_sci_rddata(), 
           .x_pcie_sci_wrdata(), .x_pcie_tx_ca_cpld_vc0(), .x_pcie_tx_ca_cplh_vc0(), 
           .x_pcie_tx_ca_npd_vc0(), .x_pcie_tx_ca_nph_vc0(), .x_pcie_tx_ca_pd_vc0(), 
           .x_pcie_tx_ca_ph_vc0(), .x_pcie_tx_data_vc0(), .x_pcie_tx_dllp_val(), 
           .x_pcie_tx_lbk_data(), .x_pcie_tx_lbk_kcntl(), .x_pcie_tx_pmtype(), 
           .x_pcie_tx_vsd_data(), .x_pcie_cmpln_tout(), .x_pcie_cmpltr_abort_np(), 
           .x_pcie_cmpltr_abort_p(), .x_pcie_dl_active(), .x_pcie_dl_inactive(), 
           .x_pcie_dl_init(), .x_pcie_dl_up(), .x_pcie_flip_lanes(), .x_pcie_force_disable_scr(), 
           .x_pcie_force_lsm_active(), .x_pcie_force_phy_status(), .x_pcie_force_rec_ei(), 
           .x_pcie_hdinn0(), .x_pcie_hdinp0(), .x_pcie_hdoutn0(), .x_pcie_hdoutp0(), 
           .x_pcie_hl_disable_scr(), .x_pcie_hl_gto_cfg(), .x_pcie_hl_gto_det(), 
           .x_pcie_hl_gto_dis(), .x_pcie_hl_gto_hrst(), .x_pcie_hl_gto_l0stx(), 
           .x_pcie_hl_gto_l0stxfts(), .x_pcie_hl_gto_l1(), .x_pcie_hl_gto_l2(), 
           .x_pcie_hl_gto_lbk(), .x_pcie_hl_gto_rcvry(), .x_pcie_hl_snd_beacon(), 
           .x_pcie_inta_n(), .x_pcie_msi_enable(), .x_pcie_no_pcie_train(), 
           .x_pcie_np_req_pend(), .x_pcie_npd_buf_status_vc0(), .x_pcie_npd_processed_vc0(), 
           .x_pcie_nph_buf_status_vc0(), .x_pcie_nph_processed_vc0(), .x_pcie_pd_buf_status_vc0(), 
           .x_pcie_pd_processed_vc0(), .x_pcie_ph_buf_status_vc0(), .x_pcie_ph_processed_vc0(), 
           .x_pcie_phy_pol_compliance(), .x_pcie_pll_refclki(), .x_pcie_pme_en(), 
           .x_pcie_pme_status(), .x_pcie_rst_n(), .x_pcie_rx_end_vc0(), 
           .x_pcie_rx_malf_tlp_vc0(), .x_pcie_rx_st_vc0(), .x_pcie_rx_us_req_vc0(), 
           .x_pcie_rxrefclk(), .x_pcie_sci_en(), .x_pcie_sci_en_dual(), 
           .x_pcie_sci_int(), .x_pcie_sci_rd(), .x_pcie_sci_sel(), .x_pcie_sci_sel_dual(), 
           .x_pcie_sci_wrn(), .x_pcie_serdes_pdb(), .x_pcie_serdes_rst_dual_c(), 
           .x_pcie_sys_clk_125(), .x_pcie_tx_ca_cpl_recheck_vc0(), .x_pcie_tx_ca_p_recheck_vc0(), 
           .x_pcie_tx_dllp_sent(), .x_pcie_tx_end_vc0(), .x_pcie_tx_lbk_rdy(), 
           .x_pcie_tx_nlfy_vc0(), .x_pcie_tx_pwrup_c(), .x_pcie_tx_rdy_vc0(), 
           .x_pcie_tx_req_vc0(), .x_pcie_tx_serdes_rst_c(), .x_pcie_tx_st_vc0(), 
           .x_pcie_unexp_cmpln(), .x_pcie_ur_np_ext(), .x_pcie_ur_p_ext(), 
           .x_cref_refclkn(), .x_cref_refclko(), .x_cref_refclkp());